(#19, #20)내 그룹 상세 페이지(진행중, 종료) 조회
again-minning/again-minning-group pull request #23
Opened 2022-01-09 14:09 UTC by solchan98

내 그룹 상세 페이지(진행중, 종료) 조회
이미지 조회 limit 설정

진행중과 종료중에 따라 상세페이지에서 불러오는 이미지 세팅이 각각 다릅니다.
진행중: 전체, 최신순
종료: 나의 이미지

따라서 요청받은 나의 그룹 ID의 상태에 따라 해당되는 조건으로 이미지를 가져옵니다.
테스트케이스는 기존 메서드와 레포 접근 외 다른 로직이 존재하지 않아 e2e테스트 케이스만 작성했습니다.
기본 limit은 10으로 설정하였고 언제는 변경 가능합니다.
이미지 더보기 등은 추가적인 API작업으로 현재 이슈로 등록되어있습니다.

혹시 빠진 부분이라던가 추가적인 예외 케이스가 있다면 알려주시면 반영하겠습니다!

Request
`/api/v1/my-group/detail?myGroupId=4&userId=10`

Response
```json
{
    "message": {
        "status": 200,
        "message": "나의 그룹 디페일 페이지를 정상적으로 조회하였습니다."
    },
    "data": {
        "title": "아침에 일어나서 러닝하기",
        "memberCnt": 4,
        "avgRate": 0,
        "description": "아침마다 러닝을 하는 그룹",
        "recommendation": "하루 한 번 달리기를 해보세요",
        "pictureDescription": "러닝하는 사진",
        "ruleDescription": "최소 1KM를 뛰어주세요.",
        "todayCnt": 3,
        "myRate": 0,
        "isDone": false,
        "dayList": [
            "MON",
            "TUE"
        ],
        "startDate": "2022-01-04T17:40:48.735Z",
        "lateDate": "2022-01-12",
        "alarmTime": null,
        "imageList": [
            {
                "image_id": "5",
                "url": "~~~",
                "created_at": "2021-12-26T13:47:34.163Z"
            }
        ]
    }
}
```
**진행중 나의 그룹 상세 페이지**
![image](https://user-images.githubusercontent.com/64524916/148685558-32d2c905-a9dc-41c8-8a1d-88ab33b555e4.png)

**종료 나의 그룹 상세 페이지**
![image](https://user-images.githubusercontent.com/64524916/148685585-d09a5e14-a61f-43be-a774-c4424f01d583.png)

2022-01-09 23:26 UTC, VIXXPARK requested changes

2022-01-09 23:26 UTC, VIXXPARK commented on src/entities/image.ts
> +  @ManyToOne(() => Group, (group) => group.imageList)
type orm에서는 many to one 에서 기본적으로 lazy인가요?

2022-01-09 23:26 UTC, VIXXPARK commented on src/group/service/group.service.ts
> +    const group = await this.groupRepository.findOne(id);
findById 하고 findOne하고 차이점이 뭔가요?

2022-01-09 23:26 UTC, VIXXPARK commented on src/image/image.repository.ts
> +      .leftJoin('i.group', 'g')
left join만 가능한가요? inner join은 없는지 궁금합니다.

2022-01-09 23:26 UTC, VIXXPARK commented on src/my-group/dto/my.group.dto.ts
> +    this.lateDate = myGroup.lastDate;
여기중에 description, recommendation, pictureDescription은 결국 설명에 관해서 묶을 수 있잖아요. 그래서 
https://orkhan.gitbook.io/typeorm/docs/embedded-entities
해당 링크를 누르면 스프링에서 @Embeddable 과 같이 쓸 수 있는 것이 있더라구요. 한 번 보시고 써보는 것도 추천합니다.

2022-01-09 23:26 UTC, VIXXPARK commented on src/entities/image.ts
> +  @PrimaryGeneratedColumn({ type: 'bigint' })
이 두개의 차이점이 뭐예요?

2022-01-10 03:57 UTC, solchan98 commented on src/entities/image.ts
> +  @ManyToOne(() => Group, (group) => group.imageList)
기본적으로 lazy도 eager도 아닙니다.
따라서 image를 가져와도 image.group 혹은 image.myGroup을 하면 쿼리를 날리는 것이 아니라 데이터가 없는 것으로 처리됩니다.

이 부분은 지난 PR때 남겼었던 [LINK](https://stackoverflow.com/questions/68983394/in-typeorm-what-are-the-default-fetch-types-for-onetomany-and-manytoone)를 보시면 알 수 있습니다.

만약 lazy 혹은 eager로 설정한다면 image를 가져올 때 group이나 myGroup을 join할 필요는 없습니다.
이 처럼 설정하고 image.group 혹은 image.myGroup을 한다면 lazy의  경우 데이터를 가져오고 eager의 경우에는 image를 가져올 때 같이 가져오기 때문에 데이터에 바로 접근이 가능합니다.

2022-01-10 03:58 UTC, solchan98 commented on src/group/service/group.service.ts
> +    const group = await this.groupRepository.findOne(id);
findById는 제가 직접 작성한 메서드입니다.
음 스프링과 비유해보면, findOne은 SpringDataJPA의 findById와 같고, 여기서의 findById는 제가 직접 작성한 QueryDSL이라고 생각하시면 편할 것 같습니다.

2022-01-10 04:16 UTC, solchan98 commented on src/image/image.repository.ts
> +      .leftJoin('i.group', 'g')
inner join도 가능합니다.
생각해보니 조회 조건이 group의 id니까 left join으로 group이 없는 image까지 필터링할 필요가 없네요?
물론 group이 없는 이미지가 저희 기획상 있을 수 가 없긴 하지만..

수한님도 같은 생각이신가요?

2022-01-10 04:18 UTC, solchan98 commented on src/entities/image.ts
> +  @PrimaryGeneratedColumn({ type: 'bigint' })
데코레이터 이름을 해석하면 그대로입니다 ㅋㅋㅋ
`@PrimaryColumn`은 말 그래로 Primary Key로 지정한다는 데코레이션입니다. (여기 primary 옵션은 제가 실수로 중복을..)
`@PrimaryGeneratedColumn`은 Primary Key로 지정하고 자동으로 넘버를 증가시키는 데코레이션입니다.

2022-01-10 04:21 UTC, solchan98 commented on src/my-group/dto/my.group.dto.ts
> +    this.lateDate = myGroup.lastDate;
오호! createdAt이나 updatedAt을 하나의 클래스로 만들어서 상속받는 방법이랑은 또 다르게 세분화 된 필드를 묶어서 보기 편하게 만들 수 있네요?!

전자는 is a 상속이고 후자는 has a 상속으로 이렇게 적용이 가능하네요!

description class를 만들어 반영해보겠습니다.

2022-01-10 05:31 UTC, VIXXPARK approved these changes

2022-01-10 05:31 UTC, VIXXPARK commented on src/entities/image.ts
> +  @ManyToOne(() => Group, (group) => group.imageList)
👌

2022-01-10 05:31 UTC, VIXXPARK commented on src/image/image.repository.ts
> +      .leftJoin('i.group', 'g')
넵넵 👍

2022-01-10 05:41 UTC, merged